service: my-next-app

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs18.x
  region: eu-central-1

functions:
  # Aquí puedes definir funciones Lambda si las necesitas

plugins:
  - serverless-finch

custom:
  client:
    bucketName: chatbot-demo-bucket
    distributionFolder: /out  
    region: eu-central-1