service: my-next-app

provider:
  name: aws
  # deploymentMethod: direct
  runtime: nodejs18.x
  region: eu-central-1

functions:
  # Aquí puedes definir funciones Lambda si las necesitas

plugins:
  - serverless-s3-deploy

custom:
  assets:
    auto: true
    targets:
       - bucket: chatbot-demo-bucket
         empty: true
         files:
          - source: out/
          
